"""initial_schema

Revision ID: 2e463ab056e5
Revises: 
Create Date: 2026-07-29 15:22:43.429724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2e463ab056e5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_devices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_box_id', sa.UUID(), nullable=False),
    sa.Column('device_token', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_token')
    )
    op.create_table('exercises',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_benchmark', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_box_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.Enum('RECURRING', 'DROP_IN', name='plancategory'), nullable=True),
    sa.Column('credits_per_week', sa.Integer(), nullable=True),
    sa.Column('validity_days', sa.Integer(), nullable=True),
    sa.Column('is_unlimited', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_box_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.Enum('COLD_PLUNGE', 'SAUNA', 'WORKSPACE', name='resourcetype'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tenant_payment_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_box_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Enum('STRIPE', 'MERCADOPAGO', 'ZELLE', 'PAGO_MOVIL', 'CASH', name='paymentprovider'), nullable=False),
    sa.Column('public_key', sa.String(length=255), nullable=True),
    sa.Column('secret_key', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_box_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('profile_picture_url', sa.String(), nullable=True),
    sa.Column('roles', postgresql.ARRAY(sa.Enum('SUPERADMIN', 'BOX_OWNER', 'STAFF', 'COACH', 'ATHLETE', 'GUEST', name='userrole')), nullable=True),
    sa.Column('athlete_type', sa.Enum('REGULAR', 'OPEN_BOX', name='athletetier'), nullable=True),
    sa.Column('biometric_reference_id', sa.String(length=255), nullable=True),
    sa.Column('booking_suspended_until', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('biometric_reference_id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_tenant_box_id'), 'users', ['tenant_box_id'], unique=False)
    op.create_table('class_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_box_id', sa.UUID(), nullable=False),
    sa.Column('track_category', sa.Enum('CROSSFIT', 'WEIGHTLIFTING', 'GYMNASTICS', 'ENDURANCE', 'HYROX', name='trackcategory'), nullable=True),
    sa.Column('coach_id', sa.UUID(), nullable=True),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('max_capacity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['coach_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_programs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_box_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('track', sa.Enum('CROSSFIT', 'WEIGHTLIFTING', 'GYMNASTICS', 'ENDURANCE', 'HYROX', name='trackcategory'), nullable=False),
    sa.Column('program_date', sa.Date(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_programs_program_date'), 'daily_programs', ['program_date'], unique=False)
    op.create_index(op.f('ix_daily_programs_tenant_box_id'), 'daily_programs', ['tenant_box_id'], unique=False)
    op.create_table('drop_in_passes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('used_on_booking_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resource_bookings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('booking_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('plan_id', sa.UUID(), nullable=True),
    sa.Column('current_weekly_credits', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('renews_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['class_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('program_blocks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('daily_program_id', sa.UUID(), nullable=True),
    sa.Column('wod_type', sa.Enum('FOR_TIME', 'AMRAP', 'EMOM', 'TABATA', 'WEIGHTLIFTING', 'OTHER', name='wodtype'), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('time_cap_seconds', sa.Integer(), nullable=True),
    sa.Column('total_rounds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['daily_program_id'], ['daily_programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('athlete_block_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('block_id', sa.UUID(), nullable=True),
    sa.Column('modality', sa.Enum('RX', 'SCALED', name='modality'), nullable=True),
    sa.Column('unit_preference', sa.Enum('KG', 'LB', name='unitofmeasure'), nullable=True),
    sa.Column('logged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('score_time_seconds', sa.Integer(), nullable=True),
    sa.Column('score_reps', sa.Integer(), nullable=True),
    sa.Column('score_rounds', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['block_id'], ['program_blocks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('program_block_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('block_id', sa.UUID(), nullable=True),
    sa.Column('exercise_id', sa.UUID(), nullable=True),
    sa.Column('prescribed_reps', sa.Integer(), nullable=True),
    sa.Column('prescribed_weight_male', sa.Float(), nullable=True),
    sa.Column('prescribed_weight_female', sa.Float(), nullable=True),
    sa.Column('prescribed_percentage', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['block_id'], ['program_blocks.id'], ),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('athlete_item_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('athlete_block_result_id', sa.UUID(), nullable=True),
    sa.Column('exercise_id', sa.UUID(), nullable=True),
    sa.Column('weight_lifted', sa.Float(), nullable=True),
    sa.Column('reps_completed', sa.Integer(), nullable=True),
    sa.Column('is_new_pr', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['athlete_block_result_id'], ['athlete_block_results.id'], ),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feed_comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('result_id', sa.UUID(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['result_id'], ['athlete_block_results.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feed_likes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('result_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['result_id'], ['athlete_block_results.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feed_likes')
    op.drop_table('feed_comments')
    op.drop_table('athlete_item_results')
    op.drop_table('program_block_items')
    op.drop_table('athlete_block_results')
    op.drop_table('program_blocks')
    op.drop_table('bookings')
    op.drop_table('user_subscriptions')
    op.drop_table('resource_bookings')
    op.drop_table('drop_in_passes')
    op.drop_index(op.f('ix_daily_programs_tenant_box_id'), table_name='daily_programs')
    op.drop_index(op.f('ix_daily_programs_program_date'), table_name='daily_programs')
    op.drop_table('daily_programs')
    op.drop_table('class_sessions')
    op.drop_index(op.f('ix_users_tenant_box_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('tenant_payment_settings')
    op.drop_table('resources')
    op.drop_table('plans')
    op.drop_table('exercises')
    op.drop_table('access_devices')
    # ### end Alembic commands ###
