"""add_change_password

Revision ID: 358aad44c4d2
Revises: 5e2b303ac67a
Create Date: 2026-07-30 02:29:06.737151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '358aad44c4d2'
down_revision: Union[str, Sequence[str], None] = '5e2b303ac67a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('requires_password_change', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'requires_password_change')
    # ### end Alembic commands ###
