"""coachs_staff

Revision ID: 5917e29a2d4e
Revises: 66174ff95042
Create Date: 2026-08-04 21:20:05.120232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5917e29a2d4e'
down_revision: Union[str, Sequence[str], None] = '66174ff95042'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instructor_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('second_last_name', sa.String(length=100), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('phone_mobile', sa.String(length=50), nullable=True),
    sa.Column('phone_landline', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=100), nullable=True),
    sa.Column('emergency_contact_relation', sa.String(length=50), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=50), nullable=True),
    sa.Column('emergency_contact_email', sa.String(length=255), nullable=True),
    sa.Column('hired_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('staff_permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('payment_management', sa.String(length=50), nullable=True),
    sa.Column('client_management', sa.String(length=50), nullable=True),
    sa.Column('instructor_management', sa.String(length=50), nullable=True),
    sa.Column('reports_access', sa.String(length=50), nullable=True),
    sa.Column('class_management', sa.String(length=50), nullable=True),
    sa.Column('booking_management', sa.String(length=50), nullable=True),
    sa.Column('can_publish_wods', sa.Boolean(), nullable=True),
    sa.Column('can_manage_wod_tv', sa.Boolean(), nullable=True),
    sa.Column('can_manage_messages', sa.Boolean(), nullable=True),
    sa.Column('clock_in_mode', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.add_column('users', sa.Column('birth_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'birth_date')
    op.drop_table('staff_permissions')
    op.drop_table('instructor_profiles')
    # ### end Alembic commands ###
