"""add_exit_time

Revision ID: 7ddee475a7f2
Revises: 6f0ee893beb4
Create Date: 2026-08-06 15:25:39.603008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ddee475a7f2'
down_revision: Union[str, Sequence[str], None] = '6f0ee893beb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gym_access_logs', sa.Column('exit_time', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gym_access_logs', 'exit_time')
    # ### end Alembic commands ###
