"""eliminated_tenants

Revision ID: e483677329a4
Revises: 358aad44c4d2
Create Date: 2026-08-03 14:43:09.772392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e483677329a4'
down_revision: Union[str, Sequence[str], None] = '358aad44c4d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('access_devices', 'tenant_box_id')
    op.drop_column('class_sessions', 'tenant_box_id')
    op.drop_index(op.f('ix_daily_programs_tenant_box_id'), table_name='daily_programs')
    op.drop_column('daily_programs', 'tenant_box_id')
    op.drop_column('plans', 'tenant_box_id')
    op.drop_column('resources', 'tenant_box_id')
    op.drop_column('tenant_payment_settings', 'tenant_box_id')
    op.drop_index(op.f('ix_users_tenant_box_id'), table_name='users')
    op.drop_constraint(op.f('users_tenant_box_id_fkey'), 'users', type_='foreignkey')
    op.drop_column('users', 'tenant_box_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tenant_box_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('users_tenant_box_id_fkey'), 'users', 'tenant_boxes', ['tenant_box_id'], ['id'])
    op.create_index(op.f('ix_users_tenant_box_id'), 'users', ['tenant_box_id'], unique=False)
    op.add_column('tenant_payment_settings', sa.Column('tenant_box_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('resources', sa.Column('tenant_box_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('plans', sa.Column('tenant_box_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('daily_programs', sa.Column('tenant_box_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_daily_programs_tenant_box_id'), 'daily_programs', ['tenant_box_id'], unique=False)
    op.add_column('class_sessions', sa.Column('tenant_box_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('access_devices', sa.Column('tenant_box_id', sa.UUID(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
