"""room_Class

Revision ID: e8d89563ba8c
Revises: 7ddee475a7f2
Create Date: 2026-08-06 17:06:23.929769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8d89563ba8c'
down_revision: Union[str, Sequence[str], None] = '7ddee475a7f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class_sessions', sa.Column('room', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('class_sessions', 'room')
    # ### end Alembic commands ###
